DROP DATABASE IF EXISTS TREASUREDB;

CREATE DATABASE TREASUREDB;

use TREASUREDB;

CREATE TABLE USER (
    USER_ID int NOT NULL AUTO_INCREMENT,
    USER_EMAIL varchar(255) UNIQUE NOT NULL,
    USER_PASS varchar(60) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE SCORE (
    SCORE_ID int NOT NULL AUTO_INCREMENT,
    USER_ID int NOT NULL,
    SCORE_DIFFICULTY int NOT NULL,
    SCORE_SCORE int NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    PRIMARY KEY (SCORE_ID)
);